packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  '@types/node': '^22.15.23'
  '@clerk/backend': '^1.33.1'
  '@types/react-dom': '18.3.1'
  '@types/react': '18.3.12'
  '@types/lodash': '^4.17.17'
  lodash: '^4.17.21'
  react-dom: '18.3.1'
  react: '18.3.1'
  wrangler: ^4.16.0
  zod: '^3.25.28'
  typescript: '^5.5.2'
  date-fns: '^4.1.0'
  'react-router-dom': '^7.6.1'
  '@trpc/server': '^11.1.3'
  'superjson': '^2.2.2'
  'vite': '^6.3.5'
  'tailwindcss': '^4.1.7'
  lucide-react: ^0.511.0
